//
// Generated By:JAX-WS RI IBM 2.0_03-01/12/2008 07:02 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/16/2007 01:18 PM(foreman)-fcs)
//


package pe.com.grupobbva.pf.rig4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

@WebService(name = "MS_PF_RIG4PortType", targetNamespace = "http://grupobbva.com.pe/pf/rig4/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MSPFRIG4PortType {


    /**
     * 
     * @param conDlgRIG4Rq
     * @return
     *     returns pe.com.grupobbva.pf.rig4.CtConDlgRIG4Rs
     */
    @WebMethod
    @WebResult(name = "ConDlgRIG4Rs", targetNamespace = "http://grupobbva.com.pe/pf/rig4/", partName = "ConDlgRIG4Rs")
    public CtConDlgRIG4Rs callrig4(
        @WebParam(name = "ConDlgRIG4Rq", targetNamespace = "http://grupobbva.com.pe/pf/rig4/", partName = "ConDlgRIG4Rq")
        CtConDlgRIG4Rq conDlgRIG4Rq);

}
