//
// Generated By:JAX-WS RI IBM 2.0_03-01/12/2008 07:02 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/16/2007 01:18 PM(foreman)-fcs)
//


package pe.com.grupobbva.pf.rig4;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "MS_PF_RIG4SOAP_HTTP_Service", targetNamespace = "http://grupobbva.com.pe/pf/rig4/", wsdlLocation = "WEB-INF/wsdl/MS_PF_RIG4Service.wsdl")
public class MSPFRIG4SOAPHTTPService
    extends Service
{

    private final static URL MSPFRIG4SOAPHTTPSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = pe.com.grupobbva.pf.rig4.MSPFRIG4SOAPHTTPService.class.getResource("/WEB-INF/wsdl/MS_PF_RIG4Service.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/MS_PF_RIG4Service.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        MSPFRIG4SOAPHTTPSERVICE_WSDL_LOCATION = url;
    }

    public MSPFRIG4SOAPHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MSPFRIG4SOAPHTTPService() {
        super(MSPFRIG4SOAPHTTPSERVICE_WSDL_LOCATION, new QName("http://grupobbva.com.pe/pf/rig4/", "MS_PF_RIG4SOAP_HTTP_Service"));
    }

    /**
     * 
     * @return
     *     returns MSPFRIG4PortType
     */
    @WebEndpoint(name = "MS_PF_RIG4SOAP_HTTP_Port")
    public MSPFRIG4PortType getMSPFRIG4SOAPHTTPPort() {
        return (MSPFRIG4PortType)super.getPort(new QName("http://grupobbva.com.pe/pf/rig4/", "MS_PF_RIG4SOAP_HTTP_Port"), MSPFRIG4PortType.class);
    }

}
