//
// Generated By:JAX-WS RI IBM 2.0_03-01/12/2008 07:02 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/16/2007 01:18 PM(foreman)-fcs)
//


package pe.com.grupobbva.pf.rig4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pe.com.grupobbva.pf.rig4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CtConDlgRIG4Rs_QNAME = new QName("http://grupobbva.com.pe/pf/rig4/", "ctConDlgRIG4Rs");
    private final static QName _ConDlgRIG4Rs_QNAME = new QName("http://grupobbva.com.pe/pf/rig4/", "ConDlgRIG4Rs");
    private final static QName _CtBodyRq_QNAME = new QName("http://grupobbva.com.pe/pf/rig4/", "ctBodyRq");
    private final static QName _CtConDlgRIG4Rq_QNAME = new QName("http://grupobbva.com.pe/pf/rig4/", "ctConDlgRIG4Rq");
    private final static QName _ConDlgRIG4Rq_QNAME = new QName("http://grupobbva.com.pe/pf/rig4/", "ConDlgRIG4Rq");
    private final static QName _CtBodyRs_QNAME = new QName("http://grupobbva.com.pe/pf/rig4/", "ctBodyRs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pe.com.grupobbva.pf.rig4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtBodyRq }
     * 
     */
    public CtBodyRq createCtBodyRq() {
        return new CtBodyRq();
    }

    /**
     * Create an instance of {@link CtBodyRs }
     * 
     */
    public CtBodyRs createCtBodyRs() {
        return new CtBodyRs();
    }

    /**
     * Create an instance of {@link CtConDlgRIG4Rq }
     * 
     */
    public CtConDlgRIG4Rq createCtConDlgRIG4Rq() {
        return new CtConDlgRIG4Rq();
    }

    /**
     * Create an instance of {@link CtConDlgRIG4Rs }
     * 
     */
    public CtConDlgRIG4Rs createCtConDlgRIG4Rs() {
        return new CtConDlgRIG4Rs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtConDlgRIG4Rs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/pf/rig4/", name = "ctConDlgRIG4Rs")
    public JAXBElement<CtConDlgRIG4Rs> createCtConDlgRIG4Rs(CtConDlgRIG4Rs value) {
        return new JAXBElement<CtConDlgRIG4Rs>(_CtConDlgRIG4Rs_QNAME, CtConDlgRIG4Rs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtConDlgRIG4Rs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/pf/rig4/", name = "ConDlgRIG4Rs")
    public JAXBElement<CtConDlgRIG4Rs> createConDlgRIG4Rs(CtConDlgRIG4Rs value) {
        return new JAXBElement<CtConDlgRIG4Rs>(_ConDlgRIG4Rs_QNAME, CtConDlgRIG4Rs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtBodyRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/pf/rig4/", name = "ctBodyRq")
    public JAXBElement<CtBodyRq> createCtBodyRq(CtBodyRq value) {
        return new JAXBElement<CtBodyRq>(_CtBodyRq_QNAME, CtBodyRq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtConDlgRIG4Rq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/pf/rig4/", name = "ctConDlgRIG4Rq")
    public JAXBElement<CtConDlgRIG4Rq> createCtConDlgRIG4Rq(CtConDlgRIG4Rq value) {
        return new JAXBElement<CtConDlgRIG4Rq>(_CtConDlgRIG4Rq_QNAME, CtConDlgRIG4Rq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtConDlgRIG4Rq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/pf/rig4/", name = "ConDlgRIG4Rq")
    public JAXBElement<CtConDlgRIG4Rq> createConDlgRIG4Rq(CtConDlgRIG4Rq value) {
        return new JAXBElement<CtConDlgRIG4Rq>(_ConDlgRIG4Rq_QNAME, CtConDlgRIG4Rq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtBodyRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/pf/rig4/", name = "ctBodyRs")
    public JAXBElement<CtBodyRs> createCtBodyRs(CtBodyRs value) {
        return new JAXBElement<CtBodyRs>(_CtBodyRs_QNAME, CtBodyRs.class, null, value);
    }

}
