//
// Generated By:JAX-WS RI IBM 2.0_03-01/12/2008 07:02 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/16/2007 01:18 PM(foreman)-fcs)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://grupobbva.com.pe/pf/rig4/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pe.com.grupobbva.pf.rig4;
